/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=flow-worker/wrangler.jsonc --include-runtime=false flow-worker/worker-configuration.d.ts` (hash: 8cf9fa26372b077d90f46660d165fc94)
interface __BaseEnv_Env {
	DYNAMIC_ENVIRONMENT_ID: "3608a494-ff5c-4cbc-a425-ddc382e4a90a";
	ALLOWED_ORIGINS: "https://bryfeng.github.io,http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173";
	DYNAMIC_API_TOKEN: string;
	ONE_DEMO_ACCESS_KEY: string;
	MERCHANT_BASE_SEPOLIA_ADDRESS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DYNAMIC_ENVIRONMENT_ID" | "ALLOWED_ORIGINS" | "DYNAMIC_API_TOKEN" | "ONE_DEMO_ACCESS_KEY" | "MERCHANT_BASE_SEPOLIA_ADDRESS">> {}
}
